module.exports={
    home:{
        fileCSS:['/css/global.css'],
        fileBlocks:[],
        fileJS:[],
        active:true
    },
    pages_maker:{
        fileCSS:['/css/global.css','/css/pages_maker.css'],
        fileBlocks:[],
        fileJS:['/js/var.js','/js/CreateTable.js','/js/pages_maker/window.js'],
        active:true
    }
}
